### ISSUE TITLE
Implement lesson edition

### ISSUE THREAD

**Issue by mquandalle** [stephane-rolland/brio#6]
We should be able to add new flashcards.

**Comment by stephane-rolland** [comment]
yes... good point.
I've been starting to think about this since you added the issue..

I happen to think that there should be default lessons, owned by let's say the system, and lessons modified by users that are owned by users...

but then, what happens if the original lesson is modified: the original lesson is owned by the system, or by an unknown original user, from which we have enriched our lesson (or let's say forked). Should our customized lesson then replicate modifications from the original lesson ( system or a different user that created that lessons we want to modify).

for the moment it's not clear for me if we should copy or reference a lesson, if we should own a lesson or not. 

Personnally, I tend to think I want to own my lessons and modify them at will.
But as I said, it's not clear yet.

**Comment by stephane-rolland** [comment]
I'm gonna meet some software craftsmen colleagues this week-end at the conference SoCraTes BE. I may discuss this idea with some of them. Maybe there will be some interesting point of views.

**Comment by stephane-rolland** [comment]
I think you were right in the first place. Lessons can come after. 

Adding and forbidding cards could/should be easy and doable during learning, just like an alternative card mode.

Wondering about elaborate lesson building as I was suggesting are probably premature for the moment.
Still thinking about it, but we'll see.
